apiVersion: apps/v1
kind: Deployment
metadata:
  name:  apinodedemo
  labels:
    app:  apinodedemo
spec:
  selector:
    matchLabels:
      app: apinodedemo
  replicas: 1
  template:
    metadata:
      labels:
        app:  apinodedemo
      annotations:
        repo: https://github.com/maxzavi/nodeapidemo
        swagger: n/a
    spec:
      containers:
      - name:  apinodedemo
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                key: host
                name: cm-db-apidemo
          - name: DB_USERNAME
            valueFrom:
              configMapKeyRef:
                key: username
                name: cm-db-apidemo
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                key: port
                name: cm-db-apidemo
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: s-db-apidemo
        image:  mzavaletav/apinodedemo:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort:  3000
          name:  port
      imagePullSecrets:
      - name: cr-mzavaletav
---
apiVersion: v1
kind: Service
metadata:
  name: apinodedemo-nodeport
spec:
  type: NodePort
  selector:
    app: apinodedemo
  ports:
    - port: 3000
      targetPort: 3000